# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         RDF-Simple
version:      0.13
version_from: lib/RDF/Simple.pm
installdirs:  site
requires:
    Class::MethodMaker:            1
    Template:                      2
    Test::Simple:                  0.44
    XML::SAX:                      0.12

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
