---
abstract: 'read and write RDF without complication'
author:
  - 'Martin Thurn mthurn@cpan.org'
build_requires:
  ExtUtils::MakeMaker: 6.42
  IO::CaptureOutput: 0
  Test::File: 0
  Test::Simple: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.82'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: RDF::Simple
name: RDF-Simple
no_index:
  directory:
    - inc
    - t
recommends:
  XML::SAX::Expat: 0
requires:
  Class::MakeMethods: 0
  File::Slurp: 0
  LWP::UserAgent: 0
  Regexp::Common: 0
  URI::Escape: 0
  XML::SAX: 0
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 0.411
